from tkinter import *
from tkinter import messagebox
root=Tk()
root.geometry("500x1000")
root.title("Registration form")
l1=Label(root,text="Registration Form",font=("bold",20))
l1.grid(row=0,columnspan=2)
label1=Label(root,text="First Name:",width=15,anchor=NW,font=("bold",18))
label1.grid(row=1)
fn1=Entry(root)
fn1.grid(row=1,column=1)
label1=Label(root,text="Father Name:",width=15,anchor=NW,font=("bold",18))
label1.grid(row=2)
fn2=Entry(root)
fn2.grid(row=2,column=1)
label1=Label(root,text="Mother Name:",width=15,anchor=NW,font=("bold",18))
label1.grid(row=3)
fn3=Entry(root)
fn3.grid(row=3,column=1)
label1=Label(root,text="E-mail:",width=15,anchor=NW,font=("bold",18))
label1.grid(row=4)
fn4=Entry(root)
fn4.grid(row=4,column=1)
label1=Label(root,text="Address:",width=15,anchor=NW,font=("bold",18))
label1.grid(row=5)
fn5=Entry(root)
fn5.grid(row=5,column=1)
label1=Label(root,text="Mobile No:",width=15,anchor=NW,font=("bold",18))
label1.grid(row=6)
fn6=Entry(root)
fn6.grid(row=6,column=1)
label1=Label(root,text="Qualification:",width=15,anchor=NW,font=("bold",18))
label1.grid(row=7)
fn7=Entry(root)
fn7.grid(row=7,column=1)
label1=Label(root,text="Date Of Birth:",width=15,anchor=NW,font=("bold",18))
label1.grid(row=8)
fn8=Entry(root)
fn8.grid(row=8,column=1)


#now main function
def submit():
    firstname=str(fn1.get())
    fathername=str(fn2.get())
    mothername=str(fn3.get())
    email=str(fn4.get())
    address=str(fn5.get())
    mobile=str(fn6.get())
    qualification=str(fn7.get())
    dob=str(fn8.get())
    # file saving data
    file=open("database.txt","a")
    file.write("\nFirst name:")
    file.write(firstname)
    file.write("\nFather name:")
    file.write(fathername)
    file.write("\nMother name:")
    file.write(mothername)
    file.write("\nE-mail:")
    file.write(email)
    file.write("\naddress:")
    file.write(address)
    file.write("\nMobile no:")
    file.write(mobile)
    file.write("\nQualification:")
    file.write(qualification)
    file.write("\nDate of birth")
    file.write(dob)
    file.write("\n============================\n")
    messagebox.showinfo("FORM","Your data inserted Sucessfully!")


b1=Button(root,text="SUBMIT",relief=RAISED,command=submit)
b1.grid(row=10)
b1=Button(root,text="EXIT",relief=RAISED,command=root.destroy)
b1.grid(row=10,column=1)
root.mainloop()
